#!/bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

wmname LG3D &
vmware-user-suid-wrapper &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         1
bspc config focused_border_color "#303032"
bspc config normal_border_color "#303032"
bspc config window_gap           12
bspc config split_ratio          0
bspc config borderless_monocle   true
bspc config gapless_monocle      true

feh --bg-fill ${HOME}/Desktop/wallpapers/2.png &

#${HOME}/.config/polybar/launch.sh &

picom --config ~/.config/picom/picom.conf &
