#!/bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

wmname LG3D &
vmware-user-suid-wrapper &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config focused_border_color "#000000"
bspc config normal_border_color "#000000"
bspc config window_gap           10
bspc config split_ratio          0
bspc config borderless_monocle   true
bspc config gapless_monocle      true

feh --bg-fill /home/kali/Desktop/wallpapers/4.jpg --no-fehbg &

# ~/.config/polybar/launch.sh &

# picom --config ~/.config/picom/picom.conf &
